version: "3.3"

services:
  redis:
    image: redis:7.0.14
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - ntwk

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - ntwk

  web:
    container_name: python_app
    build: .
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 9001
    ports:
      - 9001:9001
    volumes:
      - .:/apps
    networks:
      - ntwk

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    networks:
      - ntwk

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - ntwk
    environment:
      - PMA_ARBITRARY=1
volumes:
  redis_volume_data:
  redis_insight_volume_data:
  app:


networks:
  ntwk:
